### ISSUE TITLE
Box view: rework pagination

### ISSUE THREAD

**Issue by TheSonAlsoRises** [porygonco/porybox#345]
The current pagination comes with some issues, one of them being it is impossible to move a Pokémon from one page to another.

Ideally we would implement an autoscroll that would allow the above to be performed.

**Comment by not-an-aardvark** [comment]
We will also need to change the API for box pagination; simply having a page number isn't scalable since the server has to filter private Pokémon from the listing. For example, if a box has 3000 Pokémon, and someone other than the owner tries to view page 75/100, the server has to iterate through all of the first 74 pages in order to check which Pokémon are private; otherwise it risks disclosing the existence of a private Pokémon based on how it returns a given page.

It would be better to paginate with something like an `after` parameter, e.g.

```
GET /box/theBoxId?after=somePokemonId
```

...which would return all Pokémon in the box immediately following the given Pokémon.

**Comment by TheSonAlsoRises** [comment]
Fixed with #417.
