### ISSUE TITLE
Checking for clones

### ISSUE THREAD

**Issue by TheSonAlsoRises** [porygonco/porybox#35]
For reference:
Cloned if matches of:
- OT/TID/SID/EC
- Species
More criteria to be discussed

Acceptance criteria:
Given that the Pokémon exists in the database
Ensure that its clone status is displayed.

**Comment by TheSonAlsoRises** [comment]
Explore the possibility of an indicator displaying the likelihood of the Pokémon being a clone.

High likelihood of a clone;
- duplicate species, OT/TID/SID, EC/PID and IVs

Lower likelihood of a clone:
- same species line, OT/TID/SID, EC or/and PID

Suspicious hack
- duplicated EC/PID in the db

To be discussed.

**Comment by not-an-aardvark** [comment]
For reference, the PR (#53) will currently identify two things as clones if all of the following are identical:

> EC, OT, TID, SID, PID, IVs, species line (represented by the dex number of the first thing in the evolution chain)

I think we should probably keep the IVs in some form or another, because otherwise all static PID events will be considered clones of each other.

Since we have plans to implement hack-checking later anyway, I'm not sure we should have multiple tiers of whether something is cloned. The goal of the clone check isn't to catch people who are hacking things, it's to objectively determine whether or not two things are the same. Also, these statuses will be publicly displayed, so anyone who wants to hide the fact that their stuff is hacked will just notice the message and reupload a more subtle hacked version.

**Comment by YaManicKill** [comment]
> The goal of the clone check isn't to catch people who are hacking things, it's to objectively determine whether something is unique. 

But none of these things are definitely hacks. They just point towards a modified clone.

**Comment by TheSonAlsoRises** [comment]
After a long debate: check for OT/TID/SID/PID/EC/species line. For static PID events, also check IVs.
