### ISSUE TITLE
Create Markdown formatting guide

### ISSUE THREAD

**Issue by NotRaia** [porygonco/porybox#429]

**Comment by not-an-aardvark** [comment]
Do we need to host this on the porybox site? There are a lot of markdown guides on the internet, it'll just become one more piece of documentation that we have to maintain.

(On an unrelated note, I think we should stop adding stuff to the 1.0 milestone so that we can start using proper semantic versioning rather than "v1.0.0-betax".)

**Comment by NotRaia** [comment]
I don't think it'd require much maintenance if any at all. I dunno, I was just looking at the GitHub markdown guide (since we're using github flavored markdown) and there's a lot of stuff that would be irrelevant to Porybox users.
